
services:
  db:
    image: postgres:15-alpine
    container_name: central_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: banco_central
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: central_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  web:
    build: ./frontend-web
    container_name: client_web
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    depends_on:
      - backend