services:
  db:
    image: postgres:15-alpine
    container_name: central_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: banco_central
    ports:
      - "5433:5432"
    volumes:
      - central_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: central_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:123@db:5432/banco_central
    volumes:
      - ./backend:/app
    depends_on:
      - db

  web:
    build: ./frontend-web
    container_name: client_web
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  central_pgdata: