sonar.projectKey=miguel-zsaffioti_Habit-Tracker
sonar.organization=miguel-zsaffioti
sonar.projectName=Do.it - Habit Tracker

sonar.sources=backend,frontend-web/src,mobile-app/src

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/__pycache__/**,\
  **/*.log,\
  **/test.db,\
  **/migrations/**,\
  **/assets/**

sonar.tests=backend/tests,mobile-app/src,frontend-web/src
sonar.test.inclusions=\
  backend/tests/**,\
  mobile-app/src/**/__tests__/**,\
  mobile-app/src/**/*.test.*,\
  frontend-web/src/**/__tests__/**,\
  frontend-web/src/**/*.test.*,\
  frontend-web/src/**/*.spec.*

# Cobertura Python (backend)
sonar.python.coverage.reportPaths=coverage-backend.xml
sonar.python.version=3.11

# Cobertura JavaScript/TypeScript (frontend web + mobile)
sonar.javascript.lcov.reportPaths=frontend-web/coverage/lcov.info,mobile-app/coverage/lcov.info