sonar.projectKey=miguel-zsaffioti_Habit-Tracker
sonar.organization=miguel-zsaffioti
sonar.projectName=Do.it - Habit Tracker

sonar.sources=backend,frontend-web/src,mobile-app/src

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/__pycache__/**,\
  **/*.log,\
  **/test.db,\
  **/migrations/**,\
  **/assets/**

sonar.tests=backend/tests,mobile-app/src,frontend-web/src
sonar.test.inclusions=\
  backend/tests/**,\
  mobile-app/src/**/__tests__/**,\
  mobile-app/src/**/*.test.*,\
  frontend-web/src/**/__tests__/**,\
  frontend-web/src/**/*.test.*,\
  frontend-web/src/**/*.spec.*


sonar.python.coverage.reportPaths=coverage-backend.xml
sonar.python.version=3.11

sonar.javascript.lcov.reportPaths=frontend-web/coverage/lcov.info,mobile-app/coverage/lcov.info

sonar.coverage.exclusions=\
  mobile-app/src/app/**,\
  mobile-app/src/components/animated-icon.tsx,\
  mobile-app/src/components/animated-icon.web.tsx,\
  mobile-app/src/components/app-tabs.tsx,\
  mobile-app/src/components/app-tabs.web.tsx,\
  mobile-app/src/components/CustomDrawer.tsx,\
  mobile-app/src/components/Header.tsx,\
  mobile-app/src/components/external-link.tsx,\
  mobile-app/src/components/hint-row.tsx,\
  mobile-app/src/components/themed-text.tsx,\
  mobile-app/src/components/themed-view.tsx,\
  mobile-app/src/components/ui/**,\
  mobile-app/src/components/web-badge.tsx,\
  mobile-app/src/hooks/**,\
  mobile-app/src/constants/**