
sonar.projectKey=miguel-zsaffioti_Habit-Tracker
sonar.organization=miguel-zsaffioti
sonar.projectName=Do.it - Habit Tracker

sonar.sources=backend,frontend-web/src,mobile-app/src

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/__pycache__/**,\
  **/*.log,\
  **/test.db,\
  **/migrations/**,\
  **/assets/**

sonar.tests=backend/tests,mobile-app/src

sonar.test.inclusions=\
  backend/tests/**,\
  mobile-app/src/**/__tests__/**,\
  mobile-app/src/**/*.test.*,\
  mobile-app/src/**/*.test.ts,\
  mobile-app/src/**/*.test.tsx

sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.11